# Generated by Django 3.1.3 on 2020-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0002_auto_20201106_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
