# Generated by Django 3.1.3 on 2020-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_auto_20201107_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
